### PR TITLE
Analyze 4 packages at a time for faster results

### PR DESCRIPTION
**Pull request by ziyad-aljohani**
I asked the ai to make it analyze 4 packages instead of 1 each time, to make this works faster.

### CODE REVIEW

**Comment by berkkan22** [comment]
Thanks. I will check that out and test it

**Comment by ziyad-aljohani** [comment]
@berkkan22 Yeah please test it I didn't test it.

**Comment by berkkan22** [comment]
Wow, I'm surprised by the improvement! 
After testing with 104 packages where 100 packages were outdated, the original code averaged 11,745.6ms. However, with your code, the average dropped significantly to an impressive 3,912.8ms. A total improvement of 7,832.8ms, or 7.8 seconds.
Also, the functions still work (I mean it is just a change in the fetching so it should work).
I will update the changelog and everything and merge it in. (Either today or tomorrow)
Thanks a lot for your PR!

**Comment by ziyad-aljohani** [comment]
@berkkan22
Wow nice, 3X faster.
You're welcome mate.
And thanks for this great and unique plugin.

**Pull request merged**
